# @name get-prompts
GET http://localhost:3333/prompts

###
# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file2"; filename="teste.mp3"
Content-Type: audio/mpeg

< ./teste.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/2a7bfb09-18b6-4165-9b1f-93266dda5ec3/transcription
Content-Type: application/json

{
  "prompt": "teste"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "2a7bfb09-18b6-4165-9b1f-93266dda5ec3",
  "temperature": 0.5,
  "prompt": "Gere um resumo sucinto da transcrição do video informada a seguir: '''{transcription}'''"
}